# Site settings
title: "Sonda Sengupta"
email: "sondasengupta@example.com"
description: This is Sonda's personal page. Feel free to browse.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "sondasengupta.github.io"

twitter_username: sondasengupta
github_username:  sondasengupta

# Build settings
markdown: kramdown

highlighter: none
